import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navOptions = [
    {
      id: 1,
      name: "Home",
      route: "/",
    },
    {
      id: 2,
      name: "About Us",
      route: "#aboutus",
    },
    {
      id: 3,
      name: "Contact",
      route: "#contact",
    },
    {
      id: 4,
      name: "Guides",
      route: "#guides",
    },
  ];

  return (
    <html lang="en">
      <body className={`${inter.className} flex-col`}>
        <nav className="md:w-screen md:h-14 top-0 fixed bg-appDarkBlue flex gap-7 items-center md:px-10 ">
          {/* Navigation Options on the Left Side */}
          {navOptions.map((options) => (
            <Link
              href={options.route}
              className="list-none hover:text-appLightOrange"
              key={options.id}
            >
              {options.name}
            </Link>
          ))}
        </nav>
        {children}
      </body>
    </html>
  );
}
